version: '3'
services:
  postgres:
    image: postgres:12.1
    ports:
      - 5432:5432
  redis:
    image: redis:6.0-rc1
    ports:
      - 6379:6379
  memcached:
    image: memcached:1.5.12-alpine
    ports:
      - 11211:11211
